author: VioVioCity
main: com.vioviocity.nexus.Nexus
name: Nexus
version: 0.0.18
commands:
  test:
    description: Runs a pre-coded test.
    usage: /<command> ... who knows?
  help:
    description: Displays a list of available commands.
    usage: /<command>
  time:
    description: Displays or changes the current in-game time.
    usage: /<command> [dawn|day|dusk|night]
  weather:
    description: Displays or changes the current weather condition.
    usage: /<command> [clear|storm|thunder]
  spawn:
    description: Teleports to spawn location.
    usage: /<command>
  mode:
    description: Toggle specified player's current game mode.
    usage: /<command> (player)
  online:
    description: Displays a list of online players.
    usage: /<command>
  kick:
    description: Kicks specified player.
    usage: /<command> (player)
  ban:
    description: Bans specified player.
    usage: /<command> (player)
  unban:
    description: Unbans specified player.
    usage: /<command> (player)
  tp:
    description: Teleports player to player, also toggles incoming teleports.
    usage: /<command> (player) (player), /<command> [toggle]
  tpr:
    description: Sends teleport request to specified player, also handles teleport requests.
    usage: /<command> (player), /<command> [accept|deny|cancel]
  back:
    description: Teleports to prior location.
    usage: /<command>
  heal:
    description: Changes specified player's health and food to max.
    usage: /<command> (player)
  kill:
    description: Kills specified player.
    usage: /<command> (player)
  level:
    description: Displays and changes current level and experience.
    usage: /<command> (player) (level)
permissions:
  nexus.test:
    description: Allows use of /test.
    default: op
  nexus.help:
    description: Allows use of /help.
    default: true
  nexus.time.check:
    description: Allows use of /time.
    default: true
  nexus.time.set:
    description: Allows use of /time [dawn|day|dusk|night].
    default: op
  nexus.weather.check:
    description: Allows use of /weather.
    default: true
  nexus.weather.set:
    description: Allows use of /weather [clear|storm|thunder].
    default: op
  nexus.spawn:
    description: Allows use of /spawn.
    default: true
  nexus.spawn.set:
    description: Allows use of /spawn [set].
    default: op
  nexus.mode:
    description: Allows use of /mode (player).
    default: op
  nexus.online:
    description: Allows use of /online.
    default: true
  nexus.kick:
    description: Allows use of /kick (player).
    default: op
  nexus.ban:
    description: Allows use of /ban (player).
    default: op
  nexus.tp:
    description: Allows use of /tp (player) (player).
    default: op
  nexus.tp.toggle:
    description: Allows use of /to [toggle].
    default: op
  nexus.tpr:
    description: Allows use of /tpr (player), also /tpr [accept|deny|cancel]
    default: true
  nexus.back:
    description: Allows use of /back.
    default: true
  nexus.back.death:
    description: Allows use of /back on death.
    default: true
  nexus.heal:
    description: Allows use of /heal (player).
    default: op
  nexus.kill:
    description: Allows use of /kill (player).
    default: op
  nexus.level.check:
    description: Allows use of /xp.
    default: true
  nexus.level.set:
    description: Allows use of /xp (player) (level).
    default: op