author: Stephen Monroe (VioVioCity)
main: com.vioviocity.nexus.Nexus
name: Nexus
version: 0.1.8
commands:
  time:
    description: Displays or changes the current in-game time.
    usage: /<command> [dawn|day|dusk|night]
  weather:
    description: Displays or changes the current weather condition.
    usage: /<command> [clear|storm|thunder]
  spawn:
    description: Teleports to or changes spawn location.
    usage: /<command> [set]
  mode:
    description: Toggle specified player's current game mode.
    usage: /<command> (player)
  online:
    description: Displays a list of online players.
    usage: /<command>
  kick:
    description: Kicks specified player.
    usage: /<command> (player) (reason)
  ban:
    description: Bans specified player.
    usage: /<command> (player) (reason)
  unban:
    description: Unbans specified player.
    usage: /<command> (player)
  tp:
    description: Teleports player to player, also toggles incoming teleports.
    usage: /<command> (player) (player), /<command> [toggle]
  tpr:
    description: Sends teleport request to specified player, also handles teleport requests.
    usage: /<command> (player), /<command> [accept|deny|cancel]
  tpc:
    description: Teleports to specfied x and z coordinates
    usage: /<command> (x) (z)
  wp:
    description: Changes or teleports player to specified waypoint, also displays list of waypoints.
    usage: /<command> (waypoint) [set|delete], /<command> [list]
  home:
    description: Changes or teleports player to home location.
    usage: /<command> [set]
  back:
    description: Teleports to prior location.
    usage: /<command>
  heal:
    description: Changes specified player's health and food to max.
    usage: /<command> (player)
  kill:
    description: Kills specified player.
    usage: /<command> (player)
  level:
    description: Displays and changes current level and experience.
    usage: /<command> (player) (level)
  item:
    description: Gives specified player a quantity of an item.
    usage: /<command> (player) (id:dmg) (quantity)
  broadcast:
    description: Displays important message for all players.
    usage: /<command> (message)
  msg:
    description: Sends private message to specified player.
    usage: /<command> (player) (message)
  reply:
    description: Sends private message in response to last received private message.
    usage: /<command> (message)
  mute:
    description: Disables chat of specified player.
    usage: /<command> (player)
  unmute:
    description: Enables chat of a specified player.
    usage: /<command> (player)
  inv:
    description: Access to player inventory.
    usage: /<command (player) [clear]
permissions:
  nexus.time:
    description: Allows use of /time.
  nexus.time.set:
    description: Allows use of /time [dawn|day|dusk|night].
  nexus.weather:
    description: Allows use of /weather.
  nexus.weather.set:
    description: Allows use of /weather [clear|storm|thunder].
  nexus.spawn:
    description: Allows use of /spawn.
  nexus.spawn.set:
    description: Allows use of /spawn [set].
  nexus.mode:
    description: Allows use of /mode (player).
  nexus.online:
    description: Allows use of /online.
  nexus.kick:
    description: Allows use of /kick (player).
  nexus.ban:
    description: Allows use of /ban (player), also /unban (player).
  nexus.tp:
    description: Allows use of /tp (player) (player).
  nexus.tp.toggle:
    description: Allows use of /tp [toggle].
  nexus.tpr:
    description: Allows use of /tpr (player), also /tpr [accept|deny|cancel]
  nexus.tpc:
    description: Allows use of /tpc (x) (z)
  nexus.wp:
    description: Allows use of /wp (waypoint), also /wp [list]
  nexus.wp.set:
    description: Allows use of /wp [set]
  nexus.home:
    description: Allows use of /home
  nexus.home.set:
    description: Allows use of /home [set]
  nexus.back:
    description: Allows use of /back.
  nexus.back.death:
    description: Allows use of /back on death.
  nexus.heal:
    description: Allows use of /heal (player).
  nexus.kill:
    description: Allows use of /kill (player).
  nexus.level:
    description: Allows use of /xp.
  nexus.level.set:
    description: Allows use of /xp (player) (level).
  nexus.item:
    description: Allows use of /item (player) (id) (quantity).
  nexus.broadcast:
    description: Allows use of /broadcast (message).
  nexus.msg:
    description: Allows use of /msg (player) (message), also /reply (message).
  nexus.mute:
    description: Allows use of /mute (player), also /unmute (player)
  nexus.inv.clear:
    description: Allows use of /inv (player) [clear]