author: Stephen Monroe (VioVioCity)
main: com.vioviocity.nexus.Nexus
name: Nexus
version: 1.0.0
commands:
  time:
    description: Displays or changes the time.
    usage: /<command> [dawn|day|dusk|night]
  weather:
    description: Displays or changes the weather.
    usage: /<command> [clear|storm|thunder]
  spawn:
    description: Teleports to or changes spawn location.
    usage: /<command> [set]
  mode:
    description: Toggle specified player's current game mode.
    usage: /<command> (player)
  online:
    description: Displays a list of online players.
    usage: /<command>
  kick:
    description: Kicks specified player.
    usage: /<command> (player) (reason)
  ban:
    description: Bans specified player.
    usage: /<command> (player) (reason)
  unban:
    description: Unbans specified player.
    usage: /<command> (player)
  tp:
    description: Teleports player and toggles teleports.
    usage: /<command> (player) (player), /<command> [toggle]
  tpr:
    description: Sends teleport request to specified player.
    usage: /<command> (player), /<command> [accept|deny|cancel]
  tpc:
    description: Teleports to specfied x and z coordinates
    usage: /<command> (x) (z)
  wp:
    description: Changes or teleports player to a waypoint.
    usage: /<command> [list], /<command> [set|del] (waypoint)
  home:
    description: Changes or teleports to home location.
    usage: /<command> [set], /<command> [set|del] (home)
  back:
    description: Teleports to prior location.
    usage: /<command>
  heal:
    description: Sets player's health and food to max.
    usage: /<command> (player)
  kill:
    description: Kills specified player.
    usage: /<command> (player)
  level:
    description: Displays and changes current level.
    usage: /<command> (player) (level)
  item:
    description: Gives player a quantity of an item.
    usage: /<command> (player) (id:dmg) (quantity)
  broadcast:
    description: Displays message for all players.
    usage: /<command> (message)
  msg:
    description: Sends private message to specified player.
    usage: /<command> (player) (message)
  reply:
    description: Sends private message to last recieved.
    usage: /<command> (message)
  mute:
    description: Disables chat of specified player.
    usage: /<command> (player)
  unmute:
    description: Enables chat of a specified player.
    usage: /<command> (player)
  inv:
    description: Access to player inventory.
    usage: /<command [clear] (player)
  kit:
    description:
    usage: /<command [list], /<command> (kit)
permissions:
  nexus.time:
    description: Allows use of /time.
    default: op
  nexus.time.set:
    description: Allows use of /time [dawn|day|dusk|night].
    default: op
  nexus.weather:
    description: Allows use of /weather.
    default: op
  nexus.weather.set:
    description: Allows use of /weather [clear|storm|thunder].
    default: op
  nexus.spawn:
    description: Allows use of /spawn.
    default: op
  nexus.spawn.set:
    description: Allows use of /spawn [set].
    default: op
  nexus.mode:
    description: Allows use of /mode (player).
    default: op
  nexus.online:
    description: Allows use of /online.
    default: op
  nexus.kick:
    description: Allows use of /kick (player).
    default: op
  nexus.ban:
    description: Allows use of /ban (player), /unban (player).
    default: op
  nexus.tp:
    description: Allows use of /tp (player) (player).
    default: op
  nexus.tp.toggle:
    description: Allows use of /tp [toggle].
    default: op
  nexus.tpr:
    description: Allows use of /tpr (player), /tpr [accept|deny|cancel]
    default: op
  nexus.tpc:
    description: Allows use of /tpc (x) (z)
    default: op
  nexus.wp:
    description: Allows use of /wp (waypoint), /wp [list]
    default: op
  nexus.wp.set:
    description: Allows use of /wp [set]
    default: op
  nexus.home:
    description: Allows use of /home
    default: op
  nexus.home.set:
    description: Allows use of /home [set]
    default: op
  nexus.home.multi:
    description: Allows use of /home (home), /home [set] (home)
    default: op
  nexus.back:
    description: Allows use of /back.
    default: op
  nexus.back.death:
    description: Allows use of /back on death.
    default: op
  nexus.heal:
    description: Allows use of /heal (player).
    default: op
  nexus.kill:
    description: Allows use of /kill (player).
    default: op
  nexus.level:
    description: Allows use of /xp.
    default: op
  nexus.level.set:
    description: Allows use of /xp (player) (level).
    default: op
  nexus.item:
    description: Allows use of /item (player) (id) (quantity).
    default: op
  nexus.broadcast:
    description: Allows use of /broadcast (message).
    default: op
  nexus.msg:
    description: Allows use of /msg (player) (message), /reply (message).
    default: op
  nexus.mute:
    description: Allows use of /mute (player), /unmute (player)
    default: op
  nexus.inv.clear:
    description: Allows use of /inv (player) [clear]
    default: op
  nexus.kit:
    description: Allows use of /kit [list], /kit (kit)
    default: op